<nav class="navbar navbar-expand-lg  navbar-light style="background-color: #fbc7d4;"">

  <a class="navbar-brand" href="index.php">Meus Exercícios</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#Nav"
    aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="Nav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="index.php">Página Inicial
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="aluno.php">Aluno</a>
      </li>
    </ul>
  </div>
</nav>
